version: '3.9'

services:
  tg-bot:
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 512m
    cpus: 0.75
    restart: unless-stopped
    image: tg-bot:latest
    container_name: tg-bot
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - TZ=Europe/Minsk
    volumes:
      - ./data:/app/data
