version: "3.9"

services:
  tg-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: tg-bot:latest
    container_name: tg-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data


