name: Deploy Bot to VPS

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup and Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            # Ensure git is installed
            if ! command -v git >/dev/null 2>&1; then
              echo "git not found, installing..."
              apt-get update && apt-get install -y git
            fi

            # Ensure docker is installed
            if ! command -v docker >/dev/null 2>&1; then
              echo "Docker not found, installing..."

              apt-get update
              apt-get install -y ca-certificates curl gnupg lsb-release

              install -m 0755 -d /etc/apt/keyrings
              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
              chmod a+r /etc/apt/keyrings/docker.gpg

              echo \
                "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
                $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

              apt-get update
              apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
            fi

            # Setup directory and repository
            if [ ! -d "/root/app" ]; then
              mkdir -p /root/app
              cd /root
              git clone https://github.com/${{ github.repository }}.git app
            else
              cd /root/app
              git fetch origin main
              git reset --hard origin/main
            fi

            cd /root/app

            # Generate .env for docker compose (required by the app)
            rm -f .env
            {
              echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}";
              echo "EMAIL=${{ secrets.EMAIL }}";
              echo "FULL_NAME=${{ secrets.FULL_NAME }}";
              echo "PHONE_NUMBER=${{ secrets.PHONE_NUMBER }}";
            } > .env

            # Ensure data directory exists on host for persistence
            mkdir -p ./data

            # Build and (re)start via docker compose
            docker compose up -d --build --remove-orphans

            # Show recent logs for quick diagnostics
            docker compose logs --no-log-prefix --timestamps --since 5m | tail -n 200 || true
