name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.17.1"

      - name: Build Docker image
        run: docker build -t telegram-monitor-bot .

      - name: Save Docker image to tar
        run: docker save telegram-monitor-bot -o telegram-monitor-bot.tar

      - name: Copy Docker image to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          source: "telegram-monitor-bot.tar"
          target: "~/telegram-monitor-bot.tar"

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            docker load -i ~/telegram-monitor-bot.tar
            docker stop telegram-monitor-bot || true
            docker rm telegram-monitor-bot || true
            docker run -d --name telegram-monitor-bot --restart unless-stopped --env-file ~/capm-booking-tg-bot/.env telegram-monitor-bot
